\set ON_ERROR_STOP on
begin;
create function pg_temp.assert(ok boolean,mensaje text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception 'FALLÓ: %',mensaje; end if; end $$;
create function pg_temp.rechaza(sql text,mensaje text) returns void language plpgsql as $$ begin begin execute sql; exception when others then return; end; raise exception 'FALLÓ (no rechazó): %',mensaje; end $$;
select set_config('test.pkg',(select id::text from paquetes where nombre='Escapada Spa · NOI Casa Atacama'),true);
select set_config('test.room',(select r.id::text from habitaciones r join paquetes p on p.hotel_id=r.hotel_id where p.id=current_setting('test.pkg')::uuid and r.numero='DEMO-D01'),true);
select set_config('test.price',(select precio::text from paquetes where id=current_setting('test.pkg')::uuid),true);
select set_config('test.name',(select nombre from paquetes where id=current_setting('test.pkg')::uuid),true);
insert into auth.users(id,raw_user_meta_data) values('c0000000-0000-0000-0000-000000000001','{"rut":"77777777-7","nombre":"Cliente paquetes"}');
set local role anon;
select set_config('request.jwt.claim.sub','',true);
select pg_temp.assert(exists(select 1 from fn_disponibilidad_paquete(current_setting('test.pkg')::uuid,current_date+210,2,0) where id=current_setting('test.room')::uuid),'disponibilidad pública');
select pg_temp.rechaza(format('select fn_reservar_paquete(%L,%L,current_date+210)',current_setting('test.pkg'),current_setting('test.room')),'reserva exige sesión');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','c0000000-0000-0000-0000-000000000001',true);
select set_config('test.normal',(fn_guardar_reserva(current_setting('test.room')::uuid,current_date+200,current_date+202,2,0)).id::text,true);
select pg_temp.assert((select paquete_id is null and paquete_precio_contratado is null from reservas where id=current_setting('test.normal')::uuid),'reserva normal conserva flujo');
select set_config('test.booked',(fn_reservar_paquete(current_setting('test.pkg')::uuid,current_setting('test.room')::uuid,current_date+210,2,0)).id::text,true);
select pg_temp.assert((select paquete_precio_contratado=current_setting('test.price')::numeric and paquete_snapshot->>'nombre'=current_setting('test.name') and cliente_id=auth.uid() from reservas where id=current_setting('test.booked')::uuid),'precio y contrato del backend');
select pg_temp.assert((select monto_total=current_setting('test.price')::numeric from facturas where reserva_id=current_setting('test.booked')::uuid),'factura fija sin doble cobro de servicios');
select pg_temp.assert((select count(*)>0 and bool_and(incluido_paquete and nombre_contratado is not null) from servicios_contratados where reserva_id=current_setting('test.booked')::uuid),'servicios incluidos y nombres históricos');
select pg_temp.rechaza(format('select fn_reservar_paquete(%L,%L,current_date+211,2,0)',current_setting('test.pkg'),current_setting('test.room')),'impide solapamiento');
select pg_temp.rechaza(format('select fn_reservar_paquete(%L,%L,current_date+220,3,0)',current_setting('test.pkg'),current_setting('test.room')),'capacidad del producto');
select pg_temp.rechaza('update paquetes set precio=1','cliente no modifica precio');
select pg_temp.rechaza(format('select fn_guardar_paquete(jsonb_build_object(''hotel_id'',%L),''[]''::jsonb)',(select hotel_id from reservas where id=current_setting('test.booked')::uuid)),'cliente no administra productos');
select pg_temp.rechaza(format('select fn_reservar_paquete(p_paquete_id=>%L,p_habitacion_id=>%L,p_fecha_inicio=>current_date+220,p_precio=>1)',current_setting('test.pkg'),current_setting('test.room')),'RPC no acepta precio del navegador');
reset role;
update paquetes set nombre='Nombre nuevo',precio=precio+100000,activo=false where id=current_setting('test.pkg')::uuid;
update servicios_adicionales set nombre='Servicio renombrado',precio=123456 where id in(select servicio_id from paquete_servicios where paquete_id=current_setting('test.pkg')::uuid);
select pg_temp.assert((select paquete_precio_contratado=current_setting('test.price')::numeric and paquete_snapshot->>'nombre'=current_setting('test.name') from reservas where id=current_setting('test.booked')::uuid),'cambios del producto no alteran historia');
select pg_temp.assert(total_reserva(current_setting('test.booked')::uuid)=current_setting('test.price')::numeric,'total histórico estable');
select pg_temp.rechaza(format('update reservas set paquete_snapshot=''{}''::jsonb where id=%L',current_setting('test.booked')),'contrato inmutable incluso por escritura privilegiada');
select pg_temp.assert(not exists(select 1 from jsonb_to_recordset(fn_paquetes_publicos()) as x(id uuid) where id=current_setting('test.pkg')::uuid),'inactivo oculto al público');
set local role authenticated;
select pg_temp.rechaza(format('select fn_reservar_paquete(%L,%L,current_date+230,2,0)',current_setting('test.pkg'),current_setting('test.room')),'inactivo no reservable');
reset role;
-- Gerencia del hotel administra producto, sin poder asociar servicios de otro hotel.
insert into auth.users(id,raw_user_meta_data) values('c0000000-0000-0000-0000-000000000002','{"rut":"88888888-8","nombre":"Gerente paquetes"}');
update perfiles set rol='gerente',hotel_id=(select hotel_id from paquetes where id=current_setting('test.pkg')::uuid) where id='c0000000-0000-0000-0000-000000000002';
select set_config('test.product',(select to_jsonb(p)::text from paquetes p where id=current_setting('test.pkg')::uuid),true);
select set_config('test.services',(select jsonb_agg(jsonb_build_object('servicio_id',ps.servicio_id,'cantidad',ps.cantidad))::text from paquete_servicios ps where ps.paquete_id=current_setting('test.pkg')::uuid),true);
select set_config('test.foreign',(select jsonb_build_array(jsonb_build_object('servicio_id',s.id,'cantidad',1))::text from servicios_adicionales s where s.hotel_id<>(select hotel_id from paquetes where id=current_setting('test.pkg')::uuid) limit 1),true);
set local role authenticated;
select set_config('request.jwt.claim.sub','c0000000-0000-0000-0000-000000000002',true);
select pg_temp.assert(exists(select 1 from paquetes where id=current_setting('test.pkg')::uuid),'gerente ve producto inactivo de su hotel');
select pg_temp.rechaza(format('select fn_guardar_paquete(%L::jsonb,%L::jsonb)',current_setting('test.product'),current_setting('test.foreign')),'rechaza servicio de otro hotel');
select fn_guardar_paquete(current_setting('test.product')::jsonb||'{"activo":true,"precio":100000}'::jsonb,current_setting('test.services')::jsonb);
select pg_temp.assert((select precio=100000 and activo from paquetes where id=current_setting('test.pkg')::uuid),'gerencia edita y activa producto');
reset role;
select pg_temp.assert((select monto_total=current_setting('test.price')::numeric from facturas where reserva_id=current_setting('test.booked')::uuid),'edición administrativa no altera factura histórica');
rollback;
\echo Paquetes: contrato histórico, precio servidor, disponibilidad, RLS y reservas normales comprobados.
