/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as GerenciaRouteImport } from './routes/gerencia'
import { Route as MiCuentaRouteImport } from './routes/mi-cuenta'
import { Route as RecepcionRouteImport } from './routes/recepcion'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as HotelSlugRouteImport } from './routes/hotel.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciaRoute = GerenciaRouteImport.update({
  id: '/gerencia',
  path: '/gerencia',
  getParentRoute: () => rootRouteImport,
} as any)
const MiCuentaRoute = MiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const RecepcionRoute = RecepcionRouteImport.update({
  id: '/recepcion',
  path: '/recepcion',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelSlugRoute = HotelSlugRouteImport.update({
  id: '/hotel/$slug',
  path: '/hotel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/gerencia': typeof GerenciaRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/recepcion': typeof RecepcionRoute
  '/registro': typeof RegistroRoute
  '/hotel/$slug': typeof HotelSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/gerencia': typeof GerenciaRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/recepcion': typeof RecepcionRoute
  '/registro': typeof RegistroRoute
  '/hotel/$slug': typeof HotelSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/gerencia': typeof GerenciaRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/recepcion': typeof RecepcionRoute
  '/registro': typeof RegistroRoute
  '/hotel/$slug': typeof HotelSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/gerencia'
    | '/mi-cuenta'
    | '/recepcion'
    | '/registro'
    | '/hotel/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/gerencia'
    | '/mi-cuenta'
    | '/recepcion'
    | '/registro'
    | '/hotel/$slug'
  id:
    | '__root__'
    | '/'
    | '/acceso'
    | '/gerencia'
    | '/mi-cuenta'
    | '/recepcion'
    | '/registro'
    | '/hotel/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoRoute: typeof AccesoRoute
  GerenciaRoute: typeof GerenciaRoute
  MiCuentaRoute: typeof MiCuentaRoute
  RecepcionRoute: typeof RecepcionRoute
  RegistroRoute: typeof RegistroRoute
  HotelSlugRoute: typeof HotelSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencia': {
      id: '/gerencia'
      path: '/gerencia'
      fullPath: '/gerencia'
      preLoaderRoute: typeof GerenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-cuenta': {
      id: '/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof MiCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepcion': {
      id: '/recepcion'
      path: '/recepcion'
      fullPath: '/recepcion'
      preLoaderRoute: typeof RecepcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/$slug': {
      id: '/hotel/$slug'
      path: '/hotel/$slug'
      fullPath: '/hotel/$slug'
      preLoaderRoute: typeof HotelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoRoute: AccesoRoute,
  GerenciaRoute: GerenciaRoute,
  MiCuentaRoute: MiCuentaRoute,
  RecepcionRoute: RecepcionRoute,
  RegistroRoute: RegistroRoute,
  HotelSlugRoute: HotelSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
